services:
  db:
    image: postgres:latest
    restart: always
    container_name: carblazor_db
    environment:
      POSTGRES_USER: carblazor
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: carblazor
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/carblazor -schemas=public -user=carblazor -password=password123 -outOfOrder=true -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db

volumes:
  db: